"""
ML engine: regression coverage for Phase 5 (retiring the untrained
FraudNet/FraudGraphSAGE networks in favor of the trained XGBoost model).
"""

from conftest import TX_HEADERS, make_tx


def test_xgboost_model_is_loaded():
    """
    The trained model should load successfully in this environment (it's
    committed at app/data/xgb_model.joblib and regenerated by
    scripts/train_xgb_model.py). If this ever flips to False, scoring
    silently degrades to the noise emulator.
    """
    from app.services.ml_risk_engine import XGB_MODEL_AVAILABLE
    assert XGB_MODEL_AVAILABLE is True


def test_gnn_available_is_always_false(client):
    """The GNN path was removed — the field stays for API shape stability
    but must never claim a GNN ran."""
    tx = make_tx(amount=350000, channel="IMPS", is_cross_border=True)
    r = client.post("/transaction", json=tx, headers=TX_HEADERS)
    assert r.status_code == 200
    assert r.json()["transaction"]["gnn_available"] is False


def test_ml_predict_uses_real_model_not_pure_noise(client):
    """
    Sanity check that predict_ml_score is deterministic-ish (same inputs,
    same trained model -> same output), which the old random-noise
    emulator was not. Two identical requests through the model directly
    should return the exact same probability.
    """
    from app.services.ml_risk_engine import predict_ml_score

    tx = {"timestamp": "2026-08-07T12:00:00Z", "amount": 250000, "hop_number": 0, "simulator_meta": {}}
    account = {"tx_velocity": 3, "is_new_receiver": True}

    score1 = predict_ml_score(50.0, tx, account)
    score2 = predict_ml_score(50.0, tx, account)
    assert score1 == score2, "trained model inference must be deterministic for identical inputs"
