"""baseline schema

Mirrors the schema as it exists today (pre-Phase-0): transactions, cases,
actions (actions.case_id still has its FK to cases here, matching current
reality — it gets dropped in 0002 alongside the reason why), and the
copilot history tables. No tenant_id/idempotency_key yet — those are 0002.

Revision ID: 0001
Revises:
Create Date: 2026-09-06 13:29:22.880335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('risk_level', sa.Float(), nullable=True),
    sa.Column('total_fraud_amount', sa.Float(), nullable=True),
    sa.Column('recoverable_amount', sa.Float(), nullable=True),
    sa.Column('recovery_pct', sa.Float(), nullable=True),
    sa.Column('golden_window_minutes', sa.Integer(), nullable=True),
    sa.Column('origin_account', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_index(op.f('ix_cases_case_id'), 'cases', ['case_id'], unique=False)
    op.create_table('copilot_conversations',
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_index(op.f('ix_copilot_conversations_conversation_id'), 'copilot_conversations', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_copilot_conversations_username'), 'copilot_conversations', ['username'], unique=False)
    op.create_table('transactions',
    sa.Column('tx_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('receiver', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('threshold', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('tx_id')
    )
    op.create_index(op.f('ix_transactions_case_id'), 'transactions', ['case_id'], unique=False)
    op.create_index(op.f('ix_transactions_tx_id'), 'transactions', ['tx_id'], unique=False)
    op.create_table('actions',
    sa.Column('action_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], name='fk_actions_case_id_cases'),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_index(op.f('ix_actions_action_id'), 'actions', ['action_id'], unique=False)
    op.create_index(op.f('ix_actions_case_id'), 'actions', ['case_id'], unique=False)
    op.create_table('copilot_messages',
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('action_json', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['copilot_conversations.conversation_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_copilot_messages_conversation_id'), 'copilot_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_copilot_messages_message_id'), 'copilot_messages', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_copilot_messages_message_id'), table_name='copilot_messages')
    op.drop_index(op.f('ix_copilot_messages_conversation_id'), table_name='copilot_messages')
    op.drop_table('copilot_messages')
    op.drop_index(op.f('ix_actions_case_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_action_id'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_transactions_tx_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_case_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_copilot_conversations_username'), table_name='copilot_conversations')
    op.drop_index(op.f('ix_copilot_conversations_conversation_id'), table_name='copilot_conversations')
    op.drop_table('copilot_conversations')
    op.drop_index(op.f('ix_cases_case_id'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
